# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-01 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askaquestion',
            name='document',
        ),
        migrations.AddField(
            model_name='askaquestion',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
