# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='question_id',
            new_name='question',
        ),
    ]
