# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20180530_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askaquestion',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
