# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20180530_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='askaquestion',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='askaquestion',
            name='request',
            field=models.IntegerField(default=0),
        ),
    ]
