# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.IntegerField(default=1),
        ),
    ]
