# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0012_auto_20180530_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='hidden_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeds.AskaQuestion')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='username',
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
