# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_auto_20180531_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_msg',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
