# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_auto_20180607_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='askaquestion',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
