# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0019_auto_20180620_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askaquestion',
            name='like',
        ),
        migrations.AddField(
            model_name='askaquestion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='askaquestion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
