# Generated by Django 2.0.7 on 2018-07-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_askaquestion_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askaquestion',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
