# Generated by Django 2.0.7 on 2018-07-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_auto_20180718_0031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together=set(),
        ),
    ]
