# Generated by Django 2.0.7 on 2018-07-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0030_auto_20180720_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together=set(),
        ),
    ]
