# Generated by Django 2.0.7 on 2018-07-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0032_auto_20180720_2004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hidden',
            unique_together=set(),
        ),
    ]
