# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0039_auto_20180723_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.CharField(max_length=5000),
        ),
    ]
