# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0043_auto_20180725_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes_comment',
        ),
    ]
